# Problem #002:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# Answer: 4613732

# Solution:
def sum_even_fibonacci_numbers(max):
    result = 2
    first_term = 1
    second_term = 2

    while second_term <= max:
        next_term = first_term + second_term
        if next_term % 2 == 0:
            result += next_term
        first_term = second_term
        second_term = next_term

    return result

#Test:
print(sum_even_fibonacci_numbers(4000000))
